name: "Terraform CI"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # 🚀 This is the magic key that unlocks the manual run button!

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    env:
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan